import { CardContentsType } from 'types';

/* 임시 데이터 */
export const COBUYING_CONTENTS_LIST: CardContentsType[] = [
  {
    id: 'product20',
    title: '제목',
    thumbImage: 'img1.jpg',
    price: 10000,
    cobuying: {
      salesUnit: 'KG',
      salePeriod: '2022-09-30',
      participationNumber: 98,
      minNumber: 100,
    },
  },
  {
    id: 'product2',
    title: '제목',
    thumbImage: 'img2.jpg',
    price: 10000,
    cobuying: {
      salesUnit: 'KG',
      salePeriod: '2022-09-30',
      participationNumber: 98,
      minNumber: 100,
    },
  },
  {
    id: 'product3',
    title: '제목',
    thumbImage: 'img3.jpg',
    price: 10000,
    cobuying: {
      salesUnit: 'KG',
      salePeriod: '2022-09-30',
      participationNumber: 98,
      minNumber: 100,
    },
  },
  {
    id: 'product4',
    title: '제목',
    thumbImage: 'img2.jpg',
    price: 10000,
    cobuying: {
      salesUnit: 'KG',
      salePeriod: '2022-09-30',
      participationNumber: 98,
      minNumber: 100,
    },
  },
  {
    id: 'product5',
    title: '제목',
    thumbImage: 'img3.jpg',
    price: 10000,
    cobuying: {
      salesUnit: 'KG',
      salePeriod: '2022-09-30',
      participationNumber: 98,
      minNumber: 100,
    },
  },
  {
    id: 'product6',
    title: '제목',
    thumbImage: 'img1.jpg',
    price: 10000,
    cobuying: {
      salesUnit: 'KG',
      salePeriod: '2022-09-30',
      participationNumber: 98,
      minNumber: 100,
    },
  },
  {
    id: 'product7',
    title: '제목',
    thumbImage: 'img2.jpg',
    price: 10000,
    cobuying: {
      salesUnit: 'KG',
      salePeriod: '2022-09-30',
      participationNumber: 98,
      minNumber: 100,
    },
  },
  {
    id: 'product8',
    title: '제목',
    thumbImage: 'img3.jpg',
    price: 10000,
    cobuying: {
      salesUnit: 'KG',
      salePeriod: '2022-09-30',
      participationNumber: 98,
      minNumber: 100,
    },
  },
  {
    id: 'product9',
    title: '제목',
    thumbImage: 'img1.jpg',
    price: 10000,
    cobuying: {
      salesUnit: 'KG',
      salePeriod: '2022-09-30',
      participationNumber: 98,
      minNumber: 100,
    },
  },
  {
    id: 'product10',
    title: '제목',
    thumbImage: 'img2.jpg',
    price: 10000,
    cobuying: {
      salesUnit: 'KG',
      salePeriod: '2022-09-30',
      participationNumber: 98,
      minNumber: 100,
    },
  },
  {
    id: 'product11',
    title: '제목',
    thumbImage: 'img3.jpg',
    price: 10000,
    cobuying: {
      salesUnit: 'KG',
      salePeriod: '2022-09-30',
      participationNumber: 98,
      minNumber: 100,
    },
  },
  {
    id: 'product12',
    title: '제목',
    thumbImage: 'img2.jpg',
    price: 10000,
    cobuying: {
      salesUnit: 'KG',
      salePeriod: '2022-09-30',
      participationNumber: 98,
      minNumber: 100,
    },
  },
  {
    id: 'product13',
    title: '제목',
    thumbImage: 'img1.jpg',
    price: 10000,
    cobuying: {
      salesUnit: 'KG',
      salePeriod: '2022-09-30',
      participationNumber: 98,
      minNumber: 100,
    },
  },
  {
    id: 'product14',
    title: '제목',
    thumbImage: 'img2.jpg',
    price: 10000,
    cobuying: {
      salesUnit: 'KG',
      salePeriod: '2022-09-30',
      participationNumber: 98,
      minNumber: 100,
    },
  },
];

export const BARTER_USEDTRADE_CONTENTS_LIST: CardContentsType[] = [
  {
    id: 'product15',
    title: '제목',
    thumbImage: 'img1.jpg',
    price: 10000,
  },
  {
    id: 'product16',
    title: '제목',
    thumbImage: 'img2.jpg',
    price: 10000,
  },
  {
    id: 'product17',
    title: '제목',
    thumbImage: 'img3.jpg',
    price: 10000,
  },
  {
    id: 'product18',
    title: '제목',
    thumbImage: 'img2.jpg',
    price: 10000,
  },
  {
    id: 'product19',
    title: '제목',
    thumbImage: 'img1.jpg',
    price: 10000,
  },
  {
    id: 'product20',
    title: '제목',
    thumbImage: 'img2.jpg',
    price: 10000,
  },
  {
    id: 'product21',
    title: '제목',
    thumbImage: 'img3.jpg',
    price: 10000,
  },
  {
    id: 'product22',
    title: '제목',
    thumbImage: 'img2.jpg',
    price: 10000,
  },
  {
    id: 'product23',
    title: '제목',
    thumbImage: 'img1.jpg',
    price: 10000,
  },
  {
    id: 'product24',
    title: '제목',
    thumbImage: 'img2.jpg',
    price: 10000,
  },
  {
    id: 'product25',
    title: '제목',
    thumbImage: 'img1.jpg',
    price: 10000,
  },
  {
    id: 'product26',
    title: '제목',
    thumbImage: 'img3.jpg',
    price: 10000,
  },
  {
    id: 'product27',
    title: '제목',
    thumbImage: 'img2.jpg',
    price: 10000,
  },
];
/* */
